[package]
name = "tugger-binary-analysis"
version = "0.7.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Inspect platform binaries"
keywords = ["tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.68"
byteorder = "1.4.3"
goblin = "0.5.4"
once_cell = "1.7.2"
version-compare = "0.1.1"
