[package]
name = "tugger-debian"
version = "0.7.1"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Debian packaging primitives"
keywords = []
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
ar = "0.9"
chrono = "0.4"
libflate = "1.0"
md5 = "0.7"
os_str_bytes = "5.0"
tar = "0.4"
xz2 = "0.1"
zstd = "0.9"

[dependencies.tugger-file-manifest]
version = "0.6.0"
# path = "../tugger-file-manifest"

[dev-dependencies]
glob = "0.3"
