[package]
name = "tugger-rust-toolchain"
version = "0.13.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Discover, download, and use Rust toolchains"
keywords = ["rustup"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.68"
flate2 = "1.0.25"
fs2 = "0.4.3"
hex = "0.4.3"
log = "0.4.17"
once_cell = "1.16.0"
pgp = "0.9.0"
sha2 = "0.10.6"
simple-file-manifest = "0.11.0"
tar = "0.4.38"
toml = "0.5.10"
xz2 = { version = "0.1.7", features = ["static"] }
zstd = "0.12.1"

[dependencies.tugger-common]
version = "0.10.0-pre"
path = "../tugger-common"

[dev-dependencies]
dirs = "4.0.0"
tempfile = "3.3.0"
