[package]
name = "tugger-common"
version = "0.10.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Common functionality used by various tugger crates"
keywords = ["tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.68"
fs2 = "0.4.3"
glob = "0.3.0"
hex = "0.4.3"
log = "0.4.17"
once_cell = "1.17.0"
reqwest = { version = "0.11.13", default-features= false, features = ["blocking", "rustls-tls"] }
sha2 = "0.10.6"
tempfile = "3.3.0"
url = "2.3.1"
zip = { version = "0.6.3", default-features = false, features = ["deflate"] }
